config/routes.rb
Alpha::Application.routes.draw do
  post 'vote' => 'votes#create'
  get 'stats' => 'votes#index', as: :stats
  root 'votes#new'
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  validates_presence_of :color, :word

  def self.random(attributes = {})
    new do |vote|
      vote.word  = attributes[:word]  || random_word
      vote.color = attributes[:color] || random_color
    end
  end

  def self.random_color
    format("%06x", rand(0xFFFFFF+1))
  end

  def self.random_word
    Words.sample
  end

  def self.register(vote_params)
    @vote = Vote.where(vote_params).first || Vote.new(vote_params)
    @vote.total += 1
    @vote
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  CHOICES = Integer(ENV['OPTIONS'] || 9)

  def index
    @words = Vote.select(:word, :color, :total)
      .order(:word, :color)
      .group(:word, :color, :total)
      .group_by(&:word)
  end

  def new
    @word = Vote.random_word
    @votes = CHOICES.times.collect { Vote.random(word: @word) }
  end

  def create
    @vote = Vote.register(vote_params)

    if @vote.save
      redirect_to :root
    else
      render action: 'new'
    end
  end

private
  def vote_params
    params.require(:vote).permit(:color, :word)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_header_stats.html.haml
%header.top
  %h1
    Stats
  %nav
    = link_to :root, class: 'vote' do
      ←
      Back
      %span.cut-off to voting

app/views/layouts/_header_vote.html.haml
%header.top
  %h1
    What color best represents&nbsp;
    %span.word>= @word
    ?
  %nav
    = link_to :stats, class: 'stats' do
      ←
      %span.cut-off See the
      stats
    = link_to :root, class: 'skip' do
      Skip
      %span.cut-off this word
      →

app/views/layouts/application.html.haml
!!! 5

%html
  %head
    %title Alpha Color
    = stylesheet_link_tag "application", media: "all"
    = csrf_meta_tags

  %body
    %main= yield
    = javascript_include_tag "application"

app/views/votes/index.html.haml
= render 'layouts/header_stats'

%section.stats
  - if @words.any?
    %ul.words
      - @words.each do |word, votes|
        %li
          %strong.word= word
          %ul.votes
            - total = votes.inject(0) { |sum, vote| sum += vote.total }
            - votes.each do |vote|
              %li{style: "background-color: ##{vote.color}; width: #{Float(vote.total)/total * 100}%;", title: "##{vote.color}"}
  - else
    No colors

app/views/votes/new.html.haml
= render 'layouts/header_vote'
%nav.colors
  - @votes.each do |vote|
    = link_to "", vote_path(vote: { word: vote.word, color: vote.color }), method: :post, style: "background-color: ##{vote.color}"